### ISSUE TITLE
Feature Request: Ability to paste in ByteCode to deploy a contract

### ISSUE THREAD

**Issue by arsen3d** [dispatchlabs/scandis#24]
Often the contract is broken up among multiple files. ERC20.sol, BasicToken.sol, SafeMath.sol, etc... Right now the interface let's the user paste in code from a single file. When a developer is working on a contract on a local machine, the files can be included from different directories. While it's possible to paste code from different files and get rid of the includes, it would be better to let the developer compile on his own computer and then just paste in the Bytecode in the interface to deploy the contract to Dispatch.

**Comment by davedispatch** [comment]
This is already supported. The Bytecode and ABI fields at wallet.dispatchlabs.io are text inputs that can be pasted directly into.
